import React from 'react'

export default function Privacy () {
  return (
    <div>
      <h1>Privacy</h1>
      <ul>
        <li>Avis sur la vie privée</li>
        <li>Ce que j'utilise au quotidien (Brave, Qwant, /e/)</li>
      </ul>
      <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eamne rationem igitur sequere, qua tecum ipse et cum tuis utare, profiteri et in medium proferre non audeas? Omne enim animal, simul et ortum est, se ipsum et omnes partes suas diligit duasque, quae maximae sunt, in primis amplectitur, animum et corpus, deinde utriusque partes. Quae dici eadem de ceteris virtutibus possunt, quarum omnium fundamenta vos in voluptate tamquam in aqua ponitis. Sed si duo honesta proposita sint, alterum cum valitudine, alterum cum morbo, non esse dubium, ad utrum eorum natura nos ipsa deductura sit. Qui et definierunt plurima et definiendi artes reliquerunt, quodque est definitioni adiunctum, ut res in partes dividatur, id et fit ab illis et quem ad modum fieri oporteat traditur; Duo Reges: constructio interrete. Si movente, quod tamen dicitis, nulla turpis voluptas erit, quae praetermittenda sit, et simul non proficiscitur animal illud modo natum a summa voluptate, quae est a te posita in non dolendo. Sin autem ad animum, falsum est, quod negas animi ullum esse gaudium, quod non referatur ad corpus. Quae cum dixissem, magis ut illum provocarem quam ut ipse loquerer, tum Triarius leniter arridens: Tu quidem, inquit, totum Epicurum paene e philosophorum choro sustulisti. Teneamus enim illud necesse est, cum consequens aliquod falsum sit, illud, cuius id consequens sit, non posse esse verum. Perfecto enim et concluso neque virtutibus neque amicitiis usquam locum esse, si ad voluptatem omnia referantur, nihil praeterea est magnopere dicendum. Sed alii dolore moventur, alii cupiditate, iracundia etiam multi effetuntur et, cum in mala scientes inruunt, tum se optime sibi consulere arbitrantur. Haec videlicet est correctio philosophiae veteris et emendatio, quae omnino aditum habere nullum potest in urbem, in forum, in curiam. Quare, quotienscumque dicetur male quis de se mereri sibique esse inimicus atque hostis, vitam denique fugere, intellegatur aliquam subesse eius modi causam, ut ex eo ipso intellegi possit sibi quemque esse carum. Hac videlicet ratione, quod ea, quae externa sunt, iis tuemur officiis, quae oriuntur a suo cuiusque genere virtutis. </span>
      <span>Iam autem Callipho aut Diodorus quo modo poterunt tibi istud concedere, qui ad honestatem aliud adiungant, quod ex eodem genere non sit? Persecutus est Aristoteles animantium omnium ortus, victus, figuras, Theophrastus autem stirpium naturas omniumque fere rerum, quae e terra gignerentur, causas atque rationes; Huic Epicurus praecentet, si potest, cui e viperino morsu venae viscerum Veneno inbutae taetros cruciatus cient! Sic Epicurus: Philocteta, st! brevis dolor. Tuberonem de dolore patiendo scriberet, quod esse caput debebat, si probari posset, nusquam posuit, non esse malum dolorem, sed quid esset et quale, quantumque in eo inesset alieni, deinde quae ratio esset perferendi; In omni enim animante est summum aliquid atque optimum, ut in equis, in canibus, quibus tamen et dolore vacare opus est et valere; An, partus ancillae sitne in fructu habendus, disseretur inter principes civitatis, P. Iam ille sorites, quo nihil putatis esse vitiosius: quod bonum sit, id esse optabile, quod optabile, id expetendum, quod expetendum, id laudabile, deinde reliqui gradus. Sit voluptas non minor in nasturcio illo, quo vesci Persas esse solitos scribit Xenophon, quam in Syracusanis mensis, quae a Platone graviter vituperantur; Est enim perspicuum nullam artem ipsam in se versari, sed esse aliud artem ipsam, aliud quod propositum sit arti.</span>
    </div>
  )
}
